
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 11 15:26:33 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 5;
  public static final int NUMBER = 3;
  public static final int EOF = 0;
  public static final int SCOPE = 8;
  public static final int ASSIGN = 4;
  public static final int error = 1;
  public static final int PRINT = 7;
  public static final int IDENTIFIER = 2;
  public static final int RBRACE = 6;
}

